## This allows Github actions to build this project and publish the PDF to github.
name: Build and Tag

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: ${{ steps.get_version.outputs.VERSION }}
        prerelease: true
#         title: "Development Build"
        files: |
          ebook/target/generated-docs/building-an-api-backend-with-microprofile.pdf

#     - name: Upload binaries to release
#       uses: svenstaro/upload-release-action@v1-release
#       with:
#         repo_token: ${{ secrets.GITHUB_TOKEN }}
#         file: ebook/target/generated-docs/building-an-api-backend-with-microprofile.pdf
#         asset_name: building-an-api-backend-with-microprofile.pdf
#         tag: ${{ github.ref }}
#         overwrite: true
