## This allows Github actions to build this project and publish the PDF to github.
name: Build and Tag

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - uses: majkrzak/create-release@master
      with:
        token: ${{github.token}}
        name: My lovely release
        code: latest
        prerelease: true
        assets: >
          building-an-api-backend-with-microprofile.pdf:ebook/target/generated-docs/building-an-api-backend-with-microprofile.pdf